//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 08:25:33 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://FindReviews.giza.dariusz.com.pl/getPlace")
package pl.com.dariusz.giza.findreviews.getplace;
